### ISSUE TITLE
Fail loading mermaid layer

### ISSUE THREAD

**Issue by RidaAyed** [arnm/mermaid-layer#1]
Hi Alexi @arnm 

Thank you so much for taking your time and creating this layer :heart: 

Following your instructions in this repo and hitting `Spc f e R` opens a new window displaying:

```
** TEST: Each layer in [[file:/home/ra/.spacemacs::dotspacemacs-configuration-layers][dotspacemacs-configuration-layers]] can be found
*** PASS: org
*** FAIL: mermaid
*** PASS: ranger
```
I tried your `.spacemacs` as well (thanks for outlining the linenumbers relevant to mermaid) though the upper message remains nevertheless

Any ideas what else I could try e.g. `init.el`?

**Comment by arnm** [comment]
Sorry for getting back to you so late. I just fixed the readme. It was installing the `ob-mermaid` repo instead of this repo `mermaid-layer`... I just tried it on my machine and it seems to be working fine
