### ISSUE TITLE
Where is png file located?

### ISSUE THREAD

**Issue by anthonyclarka2** [arnm/mermaid-layer#2]
Hello, thank you so much for writing this layer!

I'm not a Spacemacs expert so I'm not sure where I'm going wrong.

I created this document:

`* Test item`
` #+begin_src mermaid :file test_mermaid.png  `
`sequenceDiagram  `
`A-->B: Works!  `
` #+end_src`

And ran SPC m b b then answered 'y' to the am I really sure question. Then this appears in the document but if I try to click on it or hit enter while the cursor is on the link, I get an error "cannot open image unknown image type". I've tested that mmdc is working correctly from the command line.

` #+RESULTS:
 [[file:test_mermaid.png]]`

Whereabouts is that png being created, and how do I open or save it?

Thank you so much

**Comment by arnm** [comment]
It'll be generated in the same location as the org file
